apiVersion: v1
kind: Service
metadata:
  name: valkey-cluster-headless
  namespace: mx-msg
  labels:
    app.kubernetes.io/instance: mx
    app.kubernetes.io/name: valkey-cluster
spec:
  clusterIP: None
  ports:
  - name: valkey-port
    port: 6379
    protocol: TCP
    targetPort: valkey-port
  - name: tcp-valkey-bus
    port: 16379
    protocol: TCP
    targetPort: tcp-valkey-bus
  selector:
    app.kubernetes.io/instance: mx
    app.kubernetes.io/name: valkey-cluster
  sessionAffinity: None
  type: ClusterIP