apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
spec:
  project: infra
  sources:
    repoURL: git@github.com:yukiosasaki/gitops-infra.git
    targetRevision: main
    path: strimzi-kafka-operator
    helm:
      valueFiles:
        - values.yaml
    epoURL: git@github.com:yukiosasaki/gitops-infra.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true

      - ServerSideApply=true
