apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:yukiosasaki/gitops-infra.git
  clusterResourceWhitelist:
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: kafka
      server: https://kubernetes.default.svc
    - namespace: valkey
      server: https://kubernetes.default.svc
  


